config/routes.rb
GamecalculationDemo::Application.routes.draw do
  
  devise_for :models
  devise_for :users, :path => "usuarios", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  root :to => "home#main"
  
  match '/last_news',  :to => "home#news"
  match '/supported_leagues',  :to => "home#supported_leagues"
  match '/assistant',  :to => "home#assistant"
  match '/algoritms',  :to => "home#algoritms"
  match '/services',  :to => "home#services"
  match '/about',  :to => "home#about"
  match '/bettings_strategy',  :to => "home#bettings_strategy"
  
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

  resources :news do 
    as_routes 
  end
  
  resources :leagues_admin do 
    as_routes 
  end
  
  match 'leagues', :to => 'leagues#index'
  match 'leagues/:id', :to => 'leagues#details'

  resources :countries_admin do
    as_routes
  end
  
  match 'countries', :to => 'countries#index'

  resources :pages do
    as_routes
  end
  
  resources :bookmakers_admin do
    as_routes
  end
  
  match 'bookmakers', :to => 'bookmakers#index'
  
  resources :betting_predictions do
    as_routes
  end
  
  resources :settings do
    as_routes
  end
  
  resources :tasks do
    as_routes
  end
  
  resources :background_tests do
    as_routes
  end
  
  match 'football_matches', :to => 'football_matches#index'
  match 'football_matches/:id', :to => 'football_matches#details'
  match 'predictions', :to => 'predictions#index'
  match 'euro2012', :to => 'euro_championship#index'
  
  resources :football_clubs_admin do
    as_routes
  end
  
  match 'football_clubs', :to => 'football_clubs#index'
  match 'football_clubs/:id', :to => 'football_clubs#details'
  
  resources :statistics
  

  
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/background_test.rb
class BackgroundTest < ActiveRecord::Base
end

app/models/betting_prediction.rb
class BettingPrediction < ActiveRecord::Base
  belongs_to :football_match
  belongs_to :bookmaker
end

app/models/bookmaker.rb
class Bookmaker < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/football_club.rb
class FootballClub < ActiveRecord::Base
end

app/models/football_match.rb
class FootballMatch < ActiveRecord::Base
  has_many :betting_prediction
  has_one :prediction
end

app/models/league.rb
class League < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
  belongs_to :football_match
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/social_communication.rb
class SocialCommunication < ActiveRecord::Base
end

app/models/statistics.rb
class Statistics < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  after_create :send_registration_confirmation_email
  
  def send_registration_confirmation_email
    @user = User.find_by_id self.id
    UserMailer.registration_confirmation(@user).deliver
  end
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base

  layout "frontend"
  require 'rss'
  require 'nokogiri'

  def index
  end
  
  def news
    @rss = RSS::Parser.parse(open('http://www.bundesliga.com/rss/en/liga/rss_news.xml').read, false) rescue nil
  end

  def supported_leagues
  end
  
  def assistant
  end
  
  def algoritms
  end
  
  def main
    @rss = RSS::Parser.parse(open('http://www.bundesliga.com/rss/en/liga/rss_news.xml').read, false) rescue nil
  end
  
  def bettings_strategy
  end
  
  def services
  end
      
  def about
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  #before_filter :authenticate_user!
  require 'rss'
  
  layout "frontend"
  
def index
    @leagues = League.find(:all)
  end
  
  def details
    @league = League.find_by_id params[:id]
    @country = Country.first(:conditions => {'alpha_3_code' => @league.country})
    @social = LeaguesSocialCommunication.first(:conditions => {:league_id => @league.id})
    
    @rss = nil
    @rss = RSS::Parser.parse(open(@social.rss).read, false) unless @social.rss.nil?
  end
end 

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_filter :authenticate_user!
  
  layout "backend"
  
  active_scaffold :news do |conf|
    config.label = "News"
    config.columns = [:title, :description, :image, :body, :is_show]
    list.sorting = {:created_at => 'DESC'}
  end
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  before_filter :authenticate_user!

  layout "backend"

  active_scaffold :page do |config|
    config.label = "Static HTML pages"
    config.columns = [:name, :alias, :title, :body]
    config.columns[:body].options = {:width => "100%"}
    
    list.sorting = {:name => 'ASC'}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/details.html.erb
<div class="leagues">
  <div>
    <div class="title">
      <div class="f_left">
        <%= image_tag "/images/#{@league.logo}", :height => "120", :alt => "#{@league.name}" %>
      </div>
      <div class="name">
        <%= @league.name.upcase %>
      </div>
    </div>
    <br />
    <br />
    <br />
    <br />
    <div class="league_info">
      <div class="item">
        Country: <%= @country.name %>
      </div>
      <div class="item">
        Web site: <%= link_to "#{@league.url}", "#{@league.url}", :target => "_blank" %>
      </div>
      <% if @league.id == 1 %>
        <div class="item">
          Football Matches: <%= link_to "visit", predictions_path %>
        </div>
      <% end %>
      <div class="item">
        Social Network:
        <% unless @social.rss.nil? %>
          <a href="<%= @social.rss %>" target="_blank">
            <%= image_tag("/images/social/feed.jpg", :border => "0", :alt => "RSS") %>
          </a>
        <% end %>
        <% unless @social.facebook.nil? %>
          <a href="<%= @social.facebook %>" target="_blank">
            <%= image_tag("/images/social/facebook.jpg", :alt => "Facebook") %>
          </a>
        <% end %>
        <% unless @social.twitter.nil? %>
          <a href="<%= @social.twitter %>" target="_blank">
            <%= image_tag("/images/social/twitter.jpg", :alt => "Twitter") %>
          </a>
        <% end %>
        <% unless @social.youtube.nil? %>
          <a href="<%= @social.youtube %>" target="_blank">
            <%= image_tag("/images/social/youtube.jpg", :alt => "YouTube") %>
          </a>
        <% end %>
        <% unless @social.google_plus.nil? %>
          <a href="<%= @social.google_plus %>" target="_blank">
            <%= image_tag("/images/social/gplus-16.png", :alt => "Google+") %>
          </a>
        <% end %>
      </div>
    </div>
    <div "latest_news">
      <h2>Latest news</h2>
      <div style="margin-left: 10px; width: 500px;">
        <% unless @rss.nil? %>
          <% @rss.items.each do |item| %>
            <div style="margin-bottom: 7px;">
              <span><%= item.pubDate.to_s[0..15] %></span><br />
              <a href="<%== item.link %>" target="_blank" ><%== item.title %></a><br />
              <span><%== item.description %></span>
            </div>
          <% end %>
        <% else %>
          <span style="silver">Coming soon</span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/leagues/index.html.erb
<div class="leagues">
  <div>
    <div class="title">
      <div class="f_left">
        <%= image_tag "/images/uefa.jpg", :height => "120px", :alt => "UEFA" %>
      </div>
      <div class="name">
       &nbsp;&nbsp;UEFA
      </div>
    </div>
  </div>
  <div class="clear"></div>
  <% @leagues.each do |league| %>
    <% unless league.name.nil? %>
      <div class="league">
        <a href=<%= "/leagues/#{league.id}" %> >
          <div class="f_left">
            <%= image_tag "/images/#{league.logo}", :height => "70" %>
          </div>
          <div class="league_name">
            <%= "#{league.name}" %>
          </div>
        </a>
      </div>
    <% end %>
  <% end %>
</div>